spring:
  datasource:
    url: jdbc:mysql://localhost:3306/messaging_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
