spring:
  datasource:
    url: jdbc:mysql://localhost:3306/messaging_system
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
      change-log: classpath:/db/changelog/changelog.yaml
server:
  port: 8088

